/*==============================================================*/
/* DBMS name:      ORACLE Version 12c                           */
/* Created on:     5/14/2019 09:46:06 PM                        */
/*==============================================================*/


alter table DICHVU_HOADON
   drop constraint FK_DICHVU_H_DICHVU_HO_DICHVU;

alter table DICHVU_HOADON
   drop constraint FK_DICHVU_H_DICHVU_HO_HOADON;

alter table HOADON
   drop constraint FK_HOADON_HOADON_PH_PHONG;

alter table HOADON
   drop constraint FK_HOADON_LAP_NHANVIEN;

alter table HOADON
   drop constraint FK_HOADON_NHAN_KHACHHAN;

alter table PHIEUDATPHONG
   drop constraint FK_PHIEUDAT_DAT_NHANVIEN;

alter table PHIEUDATPHONG
   drop constraint FK_PHIEUDAT_DAT_TRUOC_KHACHHAN;

alter table PHIEUDATPHONG
   drop constraint FK_PHIEUDAT_PHONG_PHI_PHONG;

alter table PHONG
   drop constraint FK_PHONG_THUOCC_LOAIPHON;

alter table TAIKHOAN
   drop constraint FK_TAIKHOAN_CO_NHANVIEN;

alter table TAIKHOAN
   drop constraint FK_TAIKHOAN_THUOC_LOAITAIK;

drop table DICHVU cascade constraints;

drop index DICHVU_HOADON2_FK;

drop index DICHVU_HOADON_FK;

drop table DICHVU_HOADON cascade constraints;

drop index LAP_FK;

drop index HOADON_PHONG_FK;

drop index NHAN_FK;

drop table HOADON cascade constraints;

drop table KHACHHANG cascade constraints;

drop table LOAIPHONG cascade constraints;

drop table LOAITAIKHOAN cascade constraints;

drop table NHANVIEN cascade constraints;

drop index DAT_FK;

drop index DAT_TRUOC_FK;

drop index PHONG_PHIEUDATPHONG_FK;

drop table PHIEUDATPHONG cascade constraints;

drop index THUOCC_FK;

drop table PHONG cascade constraints;

drop index THUOC_FK;

drop index CO_FK;

drop table TAIKHOAN cascade constraints;

/*==============================================================*/
/* Table: DICHVU                                                */
/*==============================================================*/
create table DICHVU (
   MADICHVU             INTEGER               not null,
   TENDICHVU            NVARCHAR2(50)         not null,
   GIATIEN              NUMBER(15)            not null,
   constraint PK_DICHVU primary key (MADICHVU)
);

/*==============================================================*/
/* Table: DICHVU_HOADON                                         */
/*==============================================================*/
create table DICHVU_HOADON (
   MADICHVU             INTEGER               not null,
   MAHOADON             INTEGER               not null,
   SOLUONG              NUMBER(5),
   THANHTIEN            NUMBER(15),
   constraint PK_DICHVU_HOADON primary key (MADICHVU, MAHOADON)
);

/*==============================================================*/
/* Index: DICHVU_HOADON_FK                                      */
/*==============================================================*/
create index DICHVU_HOADON_FK on DICHVU_HOADON (
   MADICHVU ASC
);

/*==============================================================*/
/* Index: DICHVU_HOADON2_FK                                     */
/*==============================================================*/
create index DICHVU_HOADON2_FK on DICHVU_HOADON (
   MAHOADON ASC
);

/*==============================================================*/
/* Table: HOADON                                                */
/*==============================================================*/
create table HOADON (
   MAHOADON             INTEGER               not null,
   MAPHONG              INTEGER               not null,
   MAKHACHHANG          INTEGER               not null,
   MANHANVIEN           INTEGER               not null,
   TIENPHONG            NUMBER(15)            not null,
   TIENDICHVU           NUMBER(15)            not null,
   TONGTIEN             NUMBER(15)            not null,
   NGAYDEN              DATE                  not null,
   NGAYDI               DATE                  not null,
   NGAYLAP              DATE                  not null,
   TRANGTHAI            NVARCHAR2(20)         not null,
   constraint PK_HOADON primary key (MAHOADON)
);

/*==============================================================*/
/* Index: NHAN_FK                                               */
/*==============================================================*/
create index NHAN_FK on HOADON (
   MAKHACHHANG ASC
);

/*==============================================================*/
/* Index: HOADON_PHONG_FK                                       */
/*==============================================================*/
create index HOADON_PHONG_FK on HOADON (
   MAPHONG ASC
);

/*==============================================================*/
/* Index: LAP_FK                                                */
/*==============================================================*/
create index LAP_FK on HOADON (
   MANHANVIEN ASC
);

/*==============================================================*/
/* Table: KHACHHANG                                             */
/*==============================================================*/
create table KHACHHANG (
   MAKHACHHANG          INTEGER               not null,
   HOTEN                NVARCHAR2(50)         not null,
   NGAYSINH             DATE                  not null,
   CMND                 NUMBER(20)            not null,
   GIOITINH             NVARCHAR2(5)          not null,
   DIACHI               NVARCHAR2(50)         not null,
   EMAIL                VARCHAR2(50),
   SDT                  CHAR(20)              not null,
   TRANGTHAI            NVARCHAR2(20)         not null,
   constraint PK_KHACHHANG primary key (MAKHACHHANG)
);

/*==============================================================*/
/* Table: LOAIPHONG                                             */
/*==============================================================*/
create table LOAIPHONG (
   MALOAIPHONG          INTEGER               not null,
   TENLOAIPHONG         NVARCHAR2(50)         not null,
   GIAPHONG             NUMBER(15)            not null,
   constraint PK_LOAIPHONG primary key (MALOAIPHONG)
);

/*==============================================================*/
/* Table: LOAITAIKHOAN                                          */
/*==============================================================*/
create table LOAITAIKHOAN (
   MALOAITAIKHOAN       INTEGER               not null,
   TENLOAITAIKHOAN      NVARCHAR2(50)         not null,
   MOTA                 NVARCHAR2(200),
   constraint PK_LOAITAIKHOAN primary key (MALOAITAIKHOAN)
);

/*==============================================================*/
/* Table: NHANVIEN                                              */
/*==============================================================*/
create table NHANVIEN (
   MANHANVIEN           INTEGER               not null,
   HOTEN                NVARCHAR2(50)         not null,
   NGAYSINH             DATE                  not null,
   NGAYVAOLAM           DATE                  not null,
   CMND                 NUMBER(20)            not null,
   SDT                 CHAR(20)              not null,
   MANGUOIQUANLY        INTEGER,
   GIOITINH             NVARCHAR2(5)          not null,
   EMAIL                VARCHAR2(50)          not null,
   DIACHI               NVARCHAR2(50)         not null,
   TRANGTHAI            NVARCHAR2(20)         not null,
   constraint PK_NHANVIEN primary key (MANHANVIEN)
);

/*==============================================================*/
/* Table: PHIEUDATPHONG                                         */
/*==============================================================*/
create table PHIEUDATPHONG (
   MAPHIEU              INTEGER               not null,
   MANHANVIEN           INTEGER               not null,
   MAKHACHHANG          INTEGER               not null,
   MAPHONG              INTEGER               not null,
   NGAYDAT              DATE                  not null,
   NGAYDEN              DATE                  not null,
   NGAYDI               DATE                  not null,
   constraint PK_PHIEUDATPHONG primary key (MAPHIEU)
);

/*==============================================================*/
/* Index: PHONG_PHIEUDATPHONG_FK                                */
/*==============================================================*/
create index PHONG_PHIEUDATPHONG_FK on PHIEUDATPHONG (
   MAPHONG ASC
);

/*==============================================================*/
/* Index: DAT_TRUOC_FK                                          */
/*==============================================================*/
create index DAT_TRUOC_FK on PHIEUDATPHONG (
   MAKHACHHANG ASC
);

/*==============================================================*/
/* Index: DAT_FK                                                */
/*==============================================================*/
create index DAT_FK on PHIEUDATPHONG (
   MANHANVIEN ASC
);

/*==============================================================*/
/* Table: PHONG                                                 */
/*==============================================================*/
create table PHONG (
   MAPHONG              INTEGER               not null,
   MALOAIPHONG          INTEGER               not null,
   TRANGTHAI            NVARCHAR2(20),
   constraint PK_PHONG primary key (MAPHONG)
);

/*==============================================================*/
/* Index: THUOCC_FK                                             */
/*==============================================================*/
create index THUOCC_FK on PHONG (
   MALOAIPHONG ASC
);

/*==============================================================*/
/* Table: TAIKHOAN                                              */
/*==============================================================*/
create table TAIKHOAN (
   MATAIKHOAN           INTEGER               not null,
   MANHANVIEN           INTEGER               not null,
   MALOAITAIKHOAN       INTEGER               not null,
   TENTAIKHOAN          CHAR(50)              not null,
   MATKHAU              CHAR(50)              not null,
   constraint PK_TAIKHOAN primary key (MATAIKHOAN)
);

/*==============================================================*/
/* Index: CO_FK                                                 */
/*==============================================================*/
create index CO_FK on TAIKHOAN (
   MANHANVIEN ASC
);

/*==============================================================*/
/* Index: THUOC_FK                                              */
/*==============================================================*/
create index THUOC_FK on TAIKHOAN (
   MALOAITAIKHOAN ASC
);

alter table DICHVU_HOADON
   add constraint FK_DICHVU_H_DICHVU_HO_DICHVU foreign key (MADICHVU)
      references DICHVU (MADICHVU);

alter table DICHVU_HOADON
   add constraint FK_DICHVU_H_DICHVU_HO_HOADON foreign key (MAHOADON)
      references HOADON (MAHOADON);

alter table HOADON
   add constraint FK_HOADON_HOADON_PH_PHONG foreign key (MAPHONG)
      references PHONG (MAPHONG);

alter table HOADON
   add constraint FK_HOADON_LAP_NHANVIEN foreign key (MANHANVIEN)
      references NHANVIEN (MANHANVIEN);

alter table HOADON
   add constraint FK_HOADON_NHAN_KHACHHAN foreign key (MAKHACHHANG)
      references KHACHHANG (MAKHACHHANG);

alter table PHIEUDATPHONG
   add constraint FK_PHIEUDAT_DAT_NHANVIEN foreign key (MANHANVIEN)
      references NHANVIEN (MANHANVIEN);

alter table PHIEUDATPHONG
   add constraint FK_PHIEUDAT_DAT_TRUOC_KHACHHAN foreign key (MAKHACHHANG)
      references KHACHHANG (MAKHACHHANG);

alter table PHIEUDATPHONG
   add constraint FK_PHIEUDAT_PHONG_PHI_PHONG foreign key (MAPHONG)
      references PHONG (MAPHONG);

alter table PHONG
   add constraint FK_PHONG_THUOCC_LOAIPHON foreign key (MALOAIPHONG)
      references LOAIPHONG (MALOAIPHONG);

alter table TAIKHOAN
   add constraint FK_TAIKHOAN_CO_NHANVIEN foreign key (MANHANVIEN)
      references NHANVIEN (MANHANVIEN);

alter table TAIKHOAN
   add constraint FK_TAIKHOAN_THUOC_LOAITAIK foreign key (MALOAITAIKHOAN)
      references LOAITAIKHOAN (MALOAITAIKHOAN);
alter table KHACHHANG
   add constraint FK_KHACHHANG_CO_LOAIKHACHHANG foreign key (MALOAIKHACHHANG)
      references LOAIKHACHHANG (MALOAIKHACHHANG);
--Cac procedure



--Sequence
CREATE SEQUENCE TANGDICHVU INCREMENT BY 1 START WITH 1;
CREATE OR REPLACE TRIGGER TRIG_DICHVU
BEFORE INSERT ON DICHVU
FOR EACH ROW
BEGIN
    :NEW.MADICHVU := TANGDICHVU.NEXTVAL;
END;

--Dich vu
CREATE OR REPLACE PROCEDURE PROC_THEMDICHVU(
  TENDICHVU1 DICHVU.TENDICHVU%TYPE,
  GIATIEN1 DICHVU.GIATIEN%TYPE)
AS
BEGIN
  INSERT INTO DICHVU(TENDICHVU,GIATIEN,TRANGTHAI) VALUES(TENDICHVU1,GIATIEN1,'Có');
  COMMIT;
END;

--XEM DICH VU

CREATE OR REPLACE PROCEDURE PROC_XEMDICHVU(
  CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN CONTRO FOR
  SELECT MADICHVU,TENDICHVU,GIATIEN,TRANGTHAI FROM DICHVU;
END;

-- XUAT DICH VU

CREATE OR REPLACE PROCEDURE PROC_SUADICHVU(
  TENDICHVU1 DICHVU.TENDICHVU%TYPE,
  GIATIEN1 DICHVU.GIATIEN%TYPE,
  TRANGTHAI1 DICHVU.TRANGTHAI%TYPE,
  MADICHVU1 DICHVU.MADICHVU%TYPE)
AS
BEGIN
  UPDATE DICHVU SET TENDICHVU=TENDICHVU1,GIATIEN=GIATIEN1,TRANGTHAI=TRANGTHAI1 WHERE MADICHVU=MADICHVU1;
  COMMIT;
END;



--Dat phong:
CREATE SEQUENCE TANGKHACHHANG INCREMENT BY 1 START WITH 1;
CREATE OR REPLACE TRIGGER TRIG_KH_TANG
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    :NEW.MAKHACHHANG := TANGKHACHHANG.NEXTVAL;
END;

-- NHAP THONG TIN THUE PHONG

create or replace PROCEDURE PRO_NHAPTHONGTINTHUEPHONG(HOTEN1 KHACHHANG.HOTEN%TYPE,NGAYSINH1
KHACHHANG.NGAYSINH%TYPE,CMND1 KHACHHANG.CMND%TYPE,GIOITINH1 KHACHHANG.GIOITINH%TYPE,
DIACHI1 KHACHHANG.DIACHI%TYPE,EMAIL1 KHACHHANG.EMAIL%TYPE,SDT1 KHACHHANG.SDT%TYPE,MAPHONG1 PHONG.MAPHONG%TYPE,
MANHANVIEN1 NHANVIEN.MANHANVIEN%TYPE,NGAYDEN1 HOADON.NGAYDEN%TYPE,NGAYDI1 HOADON.NGAYDI%TYPE,
MALOAIPHONG1 LOAIPHONG.MALOAIPHONG%TYPE)
AS
  COUNTT INT;
  MAKHACHHANG1 KHACHHANG.MAKHACHHANG%TYPE;
BEGIN
  SELECT COUNT(*) INTO COUNTT FROM KHACHHANG WHERE CMND=CMND1;
  IF(COUNTT=0) THEN
  INSERT INTO KHACHHANG(HOTEN,NGAYSINH,CMND,GIOITINH,TRANGTHAI,DIACHI,EMAIL,SDT) VALUES(HOTEN1,NGAYSINH1,CMND1,GIOITINH1,'T',DIACHI1,EMAIL1,SDT1);
  SELECT MAKHACHHANG INTO MAKHACHHANG1 FROM KHACHHANG WHERE CMND=CMND1;
  INSERT INTO HOADON(MAKHACHHANG,MAPHONG,MANHANVIEN,NGAYDEN,NGAYDI,NGAYLAP,TRANGTHAI) VALUES (MAKHACHHANG1,MAPHONG1,MANHANVIEN1,NGAYDEN1,NGAYDI1,SYSDATE,'C');
  END IF;
  IF(COUNTT>0) THEN
  UPDATE KHACHHANG SET TRANGTHAI='THUE' WHERE CMND=CMND1;
  SELECT MAKHACHHANG INTO MAKHACHHANG1 FROM KHACHHANG WHERE CMND=CMND1;
  INSERT INTO HOADON(MAKHACHHANG,MAPHONG,MANHANVIEN,NGAYDEN,NGAYDI,NGAYLAP,TRANGTHAI) VALUES (MAKHACHHANG1,MAPHONG1,MANHANVIEN1,NGAYDEN1,NGAYDI1,SYSDATE,'C');
  END IF;
  UPDATE PHONG SET TRANGTHAI='C' WHERE MAPHONG=MAPHONG1;
  COMMIT;
END;

--Tim kiem

--XEM NHAN VIEN

CREATE OR REPLACE PROCEDURE PROC_XEMNHANVIENTIMKIEM
(
CMND1 NHANVIEN.CMND%TYPE,
SODT1 NHANVIEN.SODT%TYPE,
DIACHI1 NHANVIEN.DIACHI%TYPE,
EMAIL1 NHANVIEN.EMAIL%TYPE,
TRANGTHAI1 NHANVIEN.TRANGTHAI%TYPE,
GIOITINH1 NHANVIEN.GIOITINH%TYPE,
HOTEN1 NHANVIEN.HOTEN%TYPE,
CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CONTRO FOR
    SELECT * FROM NHANVIEN
        WHERE (CMND LIKE '%'+CMND1+'%') OR (SODT LIKE '%SODT1%') OR  (DIACHI LIKE '%DIACHI1%') OR (EMAIL LIKE '%EMAIL1%') 
                       OR (TRANGTHAI LIKE '%TRANGTHAI1%') OR (GIOITINH LIKE '%GIOITINH1%') OR (HOTEN LIKE '%HOTEN1%');
END;

select phong.maphong,tenloaiphong,phong.trangthai,loaiphong.giaphong,khachhang.hoten, khachhang.cmnd,nhanvien.hoten,nhanvien.cmnd,
dichvu.tendichvu,dichvu_hoadon.soluong,thanhtien
from ((((((phong left join loaiphong on phong.maloaiphong=loaiphong.maloaiphong)left join hoadon on phong.maphong=hoadon.maphong) left join khachhang on hoadon.makhachhang=khachhang.makhachhang) 
left join nhanvien on hoadon.manhanvien=nhanvien.manhanvien) left join dichvu_hoadon on hoadon.mahoadon=dichvu_hoadon.mahoadon)
left join dichvu on dichvu_hoadon.madichvu=dichvu.madichvu)
order by phong.maphong;



--XEM DICH VU TIM KIEM

CREATE OR REPLACE PROCEDURE PROC_XEMDICHVUTIMKIEM
(
TENDICHVU1 DICHVU.TENDICHVU%TYPE,
GIATIEN1 DICHVU.TENDICHVU%TYPE,
TRANGTHAI1 DICHVU.TRANGTHAI%TYPE,
CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CONTRO FOR
    SELECT * FROM DICHVU
        WHERE TENDICHVU LIKE ('%'||(TENDICHVU1)||'%') OR GIATIEN LIKE ('%'||(GIATIEN1)||'%') OR TRANGTHAI LIKE ('%'||(TRANGTHAI1)||'%');
END;

---PRocedure Xuat dich vu

CREATE OR REPLACE PROCEDURE Pro_XuatDichVu(in_maphong phong.maphong%TYPE,CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT TENDICHVU, SOLUONG, THANHTIEN
FROM ((DICHVU_HOADON INNER JOIN DICHVU ON DICHVU_HOADON.MADICHVU=DICHVU.MADICHVU)
INNER JOIN HOADON ON DICHVU_HOADON.MAHOADON=HOADON.MAHOADON) 
WHERE in_maphong=maphong;
END;





--Procedure xem danh sach dat phong cua 1 phong cu the
CREATE OR REPLACE PROCEDURE PRO_THONGTINDATPHONG(IN_MAPHONG phong.maphong%TYPE, CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT PHIEUDATPHONG.MAPHIEU,PHIEUDATPHONG.MAKHACHHANG,KHACHHANG.HOTEN AS TENKHACHHANG,PHIEUDATPHONG.MANHANVIEN, NHANVIEN.HOTEN AS TENNHANVIEN, NGAYDAT ,NGAYDEN, NGAYDI
FROM (PHIEUDATPHONG INNER JOIN KHACHHANG ON PHIEUDATPHONG.MAKHACHHANG=KHACHHANG.MAKHACHHANG)
INNER JOIN NHANVIEN ON PHIEUDATPHONG.MANHANVIEN=NHANVIEN.MANHANVIEN
WHERE IN_MAPHONG=PHIEUDATPHONG.MAPHONG;
END;

-- XEM KHACH HANG TIM KIEM

CREATE OR REPLACE PROCEDURE PROC_XEMKHACHHANGTIMKIEM
(
MAKHACHHANG1 NVARCHAR2,
HOTEN1 KHACHHANG.HOTEN%TYPE,
NGAYSINH1 KHACHHANG.HOTEN%TYPE,
CMND1 NVARCHAR2,
GIOITINH1 KHACHHANG.GIOITINH%TYPE,
DIACHI1 KHACHHANG.DIACHI%TYPE,
EMAIL1 KHACHHANG.EMAIL%TYPE,
SDT1 KHACHHANG.HOTEN%TYPE,
TRANGTHAI1 KHACHHANG.TRANGTHAI%TYPE,
CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CONTRO FOR
    SELECT * FROM KHACHHANG
        WHERE MAKHACHHANG LIKE ('%'||(MAKHACHHANG1)||'%') OR HOTEN LIKE ('%'||(HOTEN1)||'%') OR
            NGAYSINH LIKE ('%'||(NGAYSINH1)||'%') OR CMND LIKE ('%'||(CMND1)||'%') OR GIOITINH LIKE ('%'||(GIOITINH1)||'%') OR
            DIACHI LIKE ('%'||(DIACHI1)||'%') OR EMAIL LIKE ('%'||(EMAIL1)||'%') OR SDT LIKE ('%'||(SDT1)||'%') OR TRANGTHAI LIKE ('%'||(TRANGTHAI1)||'%');
END;


--XEM HOA DON

CREATE OR REPLACE PROCEDURE PROC_XEMHOADON 
(CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN CONTRO FOR
    SELECT HD.MAHOADON,HD.MAPHONG,KH.HOTEN,HD.TIENPHONG,HD.TIENDICHVU,
                    HD.NGAYDEN,HD.NGAYDI,HD.NGAYLAP,NV.HOTEN,HD.TRANGTHAI,HD.TONGTIEN
        FROM HOADON HD JOIN KHACHHANG KH ON HD.MAKHACHHANG = KH.MAKHACHHANG
                                        JOIN NHANVIEN NV ON NV.MANHANVIEN=HD.MANHANVIEN;
END;

--XEM HOA DON TIM KIEM

CREATE OR REPLACE PROCEDURE PROC_XEMHOADONTIMKIEM
(
    MAPHONG1 NVARCHAR2,
    TENKHACHHANG KHACHHANG.HOTEN%TYPE,
    NGAYDEN1 NVARCHAR2,
    NGAYDI1 NVARCHAR2,
    NGAYLAP1 NVARCHAR2,
    TENNHANVIEN NHANVIEN.HOTEN%TYPE,
    TRANGTHAI1 HOADON.TRANGTHAI%TYPE,
    CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CONTRO FOR
    SELECT HD.MAHOADON,HD.MAPHONG,KH.HOTEN,HD.TIENPHONG,HD.TIENDICHVU,
                    HD.NGAYDEN,HD.NGAYDI,HD.NGAYLAP,NV.HOTEN,HD.TRANGTHAI,HD.TONGTIEN
        FROM HOADON HD JOIN KHACHHANG KH ON HD.MAKHACHHANG = KH.MAKHACHHANG
                                        JOIN NHANVIEN NV ON NV.MANHANVIEN=HD.MANHANVIEN
        WHERE HD.MAPHONG LIKE ('%'||MAPHONG1||'%') OR KH.HOTEN LIKE ('%'||TENKHACHHANG||'%') OR
                        HD.NGAYDEN LIKE (NGAYDEN1||'%') OR HD.NGAYDI LIKE (NGAYDI1||'%') OR
                        HD.NGAYLAP LIKE (NGAYLAP1||'%') OR NV.HOTEN LIKE ('%'||TENNHANVIEN||'%') OR
                        HD.TRANGTHAI LIKE ('%'||TRANGTHAI1||'%');
END;

--XEM NHAN VIEN

CREATE OR REPLACE PROCEDURE PROC_XEMNHANVIEN(
  CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN CONTRO FOR 
  SELECT A.MANHANVIEN,A.HOTEN,A.NGAYSINH,A.NGAYVAOLAM,A.CMND,A.SODT,B.HOTEN,A.GIOITINH,A.EMAIL,A.DIACHI,A.TRANGTHAI 
  FROM NHANVIEN A LEFT JOIN NHANVIEN B 
  ON A.MANGUOIQUANLY=B.MANHANVIEN;
END;


CREATE OR REPLACE PROCEDURE PROC_MANHANVIEN(
HOTEN1 NHANVIEN.HOTEN%TYPE,
CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN CONTRO FOR
    SELECT MANHANVIEN FROM NHANVIEN WHERE HOTEN=HOTEN1;
END;

--SUA NHAN VIEN

CREATE OR REPLACE PROCEDURE PROC_SUANHANVIEN(
  HOTEN1 NHANVIEN.HOTEN%TYPE,
  NGAYSINH1 NHANVIEN.NGAYSINH%TYPE,
  NGAYVAOLAM1 NHANVIEN.NGAYVAOLAM%TYPE,
  CMND1 NHANVIEN.CMND%TYPE,
  SODT1 NHANVIEN.SODT%TYPE,
  MANGUOIQUANLY1 NHANVIEN.MANGUOIQUANLY%TYPE,
  GIOITINH1 NHANVIEN.GIOITINH%TYPE,
  EMAIL1 NHANVIEN.EMAIL%TYPE,
  DIACHI1 NHANVIEN.DIACHI%TYPE,
  TRANGTHAI1 NHANVIEN.TRANGTHAI%TYPE,
  MANHANVIEN1 NHANVIEN.MANHANVIEN%TYPE
  )
AS
BEGIN
  UPDATE NHANVIEN SET HOTEN=HOTEN1,
                      NGAYSINH=NGAYSINH1,
                      NGAYVAOLAM=NGAYVAOLAM1, 
                      CMND=CMND1,
                      MANGUOIQUANLY=MANGUOIQUANLY1,
                      GIOITINH=GIOITINH1,
                      EMAIL=EMAIL1,
                      DIACHI=DIACHI1,
                      TRANGTHAI=TRANGTHAI1
                      WHERE MANHANVIEN=MANHANVIEN1;
  COMMIT;
END;


---------
create or replace TRIGGER TRIG_HOADON_TIENPHONG_TONGTIEN 

BEFORE INSERT 

ON HOADON 

FOR EACH ROW 

DECLARE 

  MAPHONG1 HOADON.MAPHONG%TYPE; 

  SONGAY INT; 

  GIAPHONG1 LOAIPHONG.GIAPHONG%TYPE; 

  TIENPHONG1 HOADON.TIENPHONG%TYPE; 

BEGIN 

  MAPHONG1:=:NEW.MAPHONG; 

  SELECT GIAPHONG INTO GIAPHONG1 FROM PHONG P JOIN LOAIPHONG LP ON P.MALOAIPHONG=LP.MALOAIPHONG WHERE MAPHONG=:NEW.MAPHONG; 

  TIENPHONG1:=GIAPHONG1*TRUNC(:NEW.NGAYDI-:NEW.NGAYDEN); 

  :NEW.TIENPHONG:=TIENPHONG1; 

  :NEW.TONGTIEN:=:NEW.TIENDICHVU+TIENPHONG1; 

END; 


--PHONG TRONG - DAT PHONG


create or replace PROCEDURE PHONGTRONG_DATPHONGA(
    NGAYDEN1 HOADON.NGAYDEN%TYPE,
    NGAYDI1 HOADON.NGAYDI%TYPE,
    MALOAIPHONG1 LOAIPHONG.MALOAIPHONG%TYPE,
    CONTRO1 OUT SYS_REFCURSOR,
    CONTRO2 OUT SYS_REFCURSOR,
    CONTRO3 OUT SYS_REFCURSOR)
  AS
  BEGIN
    OPEN CONTRO1 FOR
    SELECT MAPHONG
    FROM PHONG 
    WHERE TRANGTHAI='Trống' AND MALOAIPHONG=MALOAIPHONG1 AND MAPHONG NOT IN(SELECT MAPHONG
                                                                        FROM PHIEUDATPHONG);
    
    OPEN CONTRO2 FOR
    SELECT P.MAPHONG
    FROM PHONG P JOIN HOADON H ON P.MAPHONG=H.MAPHONG
    WHERE H.TRANGTHAI='Đã thuê' AND P.MALOAIPHONG=MALOAIPHONG1 AND NGAYDEN1>(SELECT NGAYDI
                                                                        FROM HOADON HD
                                                                        WHERE HD.MAPHONG=P.MAPHONG);
    OPEN CONTRO3 FOR
    SELECT P.MAPHONG
    FROM PHONG P JOIN PHIEUDATPHONG PDP ON P.MAPHONG=PDP.MAPHONG
    WHERE TRANGTHAI='Trống' AND P.MALOAIPHONG=MALOAIPHONG1 AND(NGAYDI1<ALL(SELECT NGAYDEN 
                                                                      FROM PHIEUDATPHONG PDP1 
                                                                      WHERE PDP1.MAPHONG=P.MAPHONG) OR (NGAYDEN1>ALL(SELECT NGAYDI 
                                                                                                                    FROM PHIEUDATPHONG PDP2   
                                                                                                                    WHERE PDP2.MAPHONG=P.MAPHONG)));
  END;
  
-- DAT TRUOC

  create or replace PROCEDURE DATTRUOC(HOTEN1 KHACHHANG.HOTEN%TYPE,
  NGAYSINH1 KHACHHANG.NGAYSINH%TYPE,
  CMND1 KHACHHANG.CMND%TYPE,
  GIOITINH1 KHACHHANG.GIOITINH%TYPE,
  DIACHI1 KHACHHANG.DIACHI%TYPE,
  EMAIL1 KHACHHANG.EMAIL%TYPE,
  SODT1 KHACHHANG.SDT%TYPE,
  MAPHONG1 PHONG.MAPHONG%TYPE,
  MANHANVIEN1 NHANVIEN.MANHANVIEN%TYPE,
  NGAYDEN1 PHIEUDATPHONG.NGAYDEN%TYPE,
  NGAYDI1 PHIEUDATPHONG.NGAYDI%TYPE)
AS
  COUNTT INT;
  MAKHACHHANG1 KHACHHANG.MAKHACHHANG%TYPE;
BEGIN
    SELECT COUNT(*) INTO COUNTT FROM KHACHHANG WHERE CMND=CMND1;
    IF(COUNTT=0) THEN
      INSERT INTO KHACHHANG(HOTEN,NGAYSINH,CMND,GIOITINH,TRANGTHAI,DIACHI,EMAIL,SDT) VALUES(HOTEN1,NGAYSINH1,CMND1,GIOITINH1,'Đang đặt trước',DIACHI1,EMAIL1,SODT1);
      SELECT MAKHACHHANG INTO MAKHACHHANG1 FROM KHACHHANG WHERE CMND=CMND1;
      INSERT INTO PHIEUDATPHONG(MAKHACHHANG,MANHANVIEN,MAPHONG,NGAYDAT,NGAYDEN,NGAYDI) VALUES(MAKHACHHANG1,MANHANVIEN1,MAPHONG1,SYSDATE,NGAYDEN1,NGAYDI1);
    END IF;
    IF(COUNTT>0) THEN
    UPDATE KHACHHANG SET TRANGTHAI='Đang đặt trước' WHERE CMND=CMND1;
    SELECT MAKHACHHANG INTO MAKHACHHANG1 FROM KHACHHANG WHERE CMND=CMND1;
    INSERT INTO PHIEUDATPHONG(MAKHACHHANG,MANHANVIEN,MAPHONG,NGAYDAT,NGAYDEN,NGAYDI) VALUES(MAKHACHHANG1,MANHANVIEN1,MAPHONG1,SYSDATE,NGAYDEN1,NGAYDI1);
    END IF;
END;

-- LOAD PHIEU DAT PHONG

CREATE OR REPLACE PROCEDURE PRO_LOADPHIEUDATPHONG(CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT MAPHIEU,PHIEUDATPHONG.MAKHACHHANG,KHACHHANG.HOTEN,PHIEUDATPHONG.MANHANVIEN,NHANVIEN.HOTEN,MAPHONG,NGAYDAT,NGAYDEN,NGAYDI
FROM ((PHIEUDATPHONG INNER JOIN KHACHHANG ON PHIEUDATPHONG.MAKHACHHANG=KHACHHANG.MAKHACHHANG)
INNER JOIN NHANVIEN ON PHIEUDATPHONG.MANHANVIEN=NHANVIEN.MANHANVIEN);
END;

--THONG KE THANG

CREATE OR REPLACE PROCEDURE PROC_THONGKE_THANG(
  NGAYBD DATE,
  NGAYKT DATE,
  CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN CONTRO FOR 
  SELECT SUM(TONGTIEN),EXTRACT(MONTH FROM NGAYDI),EXTRACT(YEAR FROM NGAYDI)
  FROM HOADON
  WHERE NGAYDI >= NGAYBD AND NGAYDI <= NGAYKT
                        AND TRANGTHAI='Đã thanh toán'
   GROUP BY  EXTRACT(MONTH FROM NGAYDI),EXTRACT(YEAR FROM NGAYDI)
   ORDER BY EXTRACT(YEAR FROM NGAYDI),EXTRACT (MONTH FROM NGAYDI);
END;

--THONG KE NAM

CREATE OR REPLACE PROCEDURE PROC_THONGKE_NAM(
  NGAYBD DATE,
  NGAYKT DATE,
  CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN CONTRO FOR 
  SELECT SUM(TONGTIEN),EXTRACT(YEAR FROM NGAYDI)
  FROM HOADON
  WHERE NGAYDI >= NGAYBD AND NGAYDI <= NGAYKT
                        AND TRANGTHAI='Đã thanh toán'
   GROUP BY  EXTRACT(YEAR FROM NGAYDI)
   ORDER BY EXTRACT (YEAR FROM NGAYDI);
END;

--THON GKE TONG DOANH THU

CREATE OR REPLACE PROCEDURE PROC_THONGKETONGDOANHTHU(
  TUNGAY DATE,
  DENNGAY DATE,
  TONGDOANHTHU OUT NUMBER)
AS
BEGIN
  SELECT SUM(TONGTIEN)
  INTO TONGDOANHTHU
  FROM HOADON
  WHERE NGAYDI<=DENNGAY AND NGAYDI>=TUNGAY AND TRANGTHAI='D';
END;

--Su ly TIM KIEM, nhan phong, huy, cap nhat
CREATE SEQUENCE TANGPHIEUDATPHONG INCREMENT BY 1 START WITH 1;
CREATE OR REPLACE TRIGGER TRIG_PHIEUDATPHONG
BEFORE INSERT ON PHIEUDATPHONG
FOR EACH ROW
BEGIN
    :NEW.MAPHIEU := TANGPHIEUDATPHONG.NEXTVAL;
END;


CREATE OR REPLACE PROCEDURE PRO_TIMKIEM_PHIEUDATPHONG(
IN_MAPHIEU KHACHHANG.HOTEN%TYPE,
IN_TENKHACHHANG KHACHHANG.HOTEN%TYPE,
IN_TENNHANVIEN NHANVIEN.HOTEN%TYPE,
IN_MAPHONG KHACHHANG.HOTEN%TYPE,
CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
OPEN CONTRO FOR
SELECT MAPHIEU,PHIEUDATPHONG.MAKHACHHANG,A.HOTEN,PHIEUDATPHONG.MANHANVIEN,B.HOTEN,MAPHONG,NGAYDAT,NGAYDEN,NGAYDI
FROM ((PHIEUDATPHONG INNER JOIN KHACHHANG  A ON PHIEUDATPHONG.MAKHACHHANG=A.MAKHACHHANG)
INNER JOIN NHANVIEN B ON PHIEUDATPHONG.MANHANVIEN=B.MANHANVIEN)
WHERE MAPHIEU LIKE ('%'||IN_MAPHIEU||'%')
OR A.HOTEN LIKE ('%'||IN_TENKHACHHANG||'%')
OR B.HOTEN LIKE ('%'||IN_TENNHANVIEN||'%')
OR MAPHONG LIKE ('%'||IN_MAPHONG||'%');
END;

CREATE OR REPLACE PROCEDURE PRO_HUY_PHIEUDATPHONG(
IN_MAPHIEU PHIEUDATPHONG.MAPHIEU%TYPE)
AS
BEGIN
DELETE FROM PHIEUDATPHONG
WHERE MAPHIEU=IN_MAPHIEU;
COMMIT;
END;

CREATE OR REPLACE PROCEDURE PRO_UPDATE_PHIEUDATPHONG(
IN_MAPHONG PHIEUDATPHONG.MAPHONG%TYPE,
IN_NGAYDEN PHIEUDATPHONG.NGAYDEN%TYPE,
IN_NGAYDI PHIEUDATPHONG.NGAYDI%TYPE,
IN_MAPHIEU PHIEUDATPHONG.MAPHIEU%TYPE)
AS
BEGIN
UPDATE PHIEUDATPHONG
SET MAPHONG=IN_MAPHONG, NGAYDEN=IN_NGAYDEN, NGAYDI=IN_NGAYDI, NGAYDAT=SYSDATE
WHERE MAPHIEU=IN_MAPHIEU;
END;

CREATE OR REPLACE PROCEDURE PRO_NHANPHONG_PHIEUDATPHONG(
IN_MAPHONG HOADON.MAPHONG%TYPE,
IN_MAKHACHHANG HOADON.MAKHACHHANG%TYPE,
IN_MANHANVIEN HOADON.MANHANVIEN%TYPE,
IN_NGAYDEN HOADON.NGAYDEN%TYPE,
IN_NGAYDI HOADON.NGAYDI%TYPE
)
AS
BEGIN
INSERT INTO HOADON(MAPHONG,MAKHACHHANG,MANHANVIEN,NGAYDEN,NGAYDI,NGAYLAP,TRANGTHAI)
VALUES(IN_MAPHONG,IN_MAKHACHHANG, IN_MANHANVIEN,IN_NGAYDEN,IN_NGAYDI,SYSDATE,'C');

UPDATE PHONG
SET TRANGTHAI='C'
WHERE IN_MAPHONG=MAPHONG;

DELETE FROM PHIEUDATPHONG
WHERE MANHANVIEN=IN_MANHANVIEN AND MAKHACHHANG=IN_MAKHACHHANG
AND MAPHONG=IN_MAPHONG AND NGAYDEN=IN_NGAYDEN AND NGAYDI=IN_NGAYDI;

UPDATE KHACHHANG
SET TRANGTHAI='Đang thuê'
WHERE MAKHACHHANG=IN_MAKHACHHANG;

END;





--Them nhan Vien
CREATE OR REPLACE PROCEDURE PROC_THEMNHANVIEN(
  HOTEN1 NHANVIEN.HOTEN%TYPE,
  NGAYSINH1 NHANVIEN.NGAYSINH%TYPE,
  NGAYVAOLAM1 NHANVIEN.NGAYVAOLAM%TYPE,
  CMND1 NHANVIEN.CMND%TYPE,
  SODT1 NHANVIEN.SODT%TYPE,
  GIOITINH1 NHANVIEN.GIOITINH%TYPE,
  EMAIL1 NHANVIEN.EMAIL%TYPE,
  DIACHI1 NHANVIEN.DIACHI%TYPE,
  TRANGTHAI1 NHANVIEN.TRANGTHAI%TYPE,
  MANGUOIQUANLY1 NHANVIEN.MANGUOIQUANLY%TYPE
  )
AS
BEGIN
  INSERT INTO NHANVIEN(HOTEN,NGAYSINH,NGAYVAOLAM,CMND,SODT,GIOITINH,EMAIL,TRANGTHAI,DIACHI,MANGUOIQUANLY) VALUES(HOTEN1,NGAYSINH1,NGAYVAOLAM1,CMND1,SODT1,GIOITINH1,EMAIL1,TRANGTHAI1,DIACHI1,MANGUOIQUANLY1);
  COMMIT;
END;

--TAI KHOAN
CREATE OR REPLACE PROCEDURE PRO_LOADTAIKHOAN(CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT * FROM TAIKHOAN;
END;

--Tim kiem o phong




--Procedure khachhang

SELECT HOADON.MAHOADON,MADICHVU,SOLUONG,THANHTIEN
FROM HOADON LEFT JOIN DICHVU_HOADON ON HOADON.MAHOADON=HOADON.MAHOADON
ORDER BY MAHOADON,MADICHVU;

SELECT KH.MAKHACHHANG,KH.HOTEN,KH.CMND,KH.DIACHI,KH.NGAYSINH,KH.SDT,HD.TONGTIEN,hd.mahoadon,hd.ngaylap
FROM HOADON HD JOIN KHACHHANG KH ON HD.MAKHACHHANG=KH.MAKHACHHANG
WHERE HD.TRANGTHAI='Đã thanh toán'
ORDER BY KH.MAKHACHHANG ASC, HD.MAHOADON ASC

--cap nhat khach hang
CREATE OR REPLACE PROCEDURE PRO_CAPNHATKHACHHANG(
IN_MAKHACHHANG KHACHHANG.MAKHACHHANG%TYPE,
IN_HOTEN KHACHHANG.HOTEN%TYPE,
IN_NGAYSINH KHACHHANG.NGAYSINH%TYPE,
IN_CMND KHACHHANG.CMND%TYPE,
IN_GIOITINH KHACHHANG.GIOITINH%TYPE,
IN_DIACHI KHACHHANG.DIACHI%TYPE,
IN_EMAIL KHACHHANG.EMAIL%TYPE,
IN_SDT KHACHHANG.SDT%TYPE,
IN_TRANGTHAI KHACHHANG.TRANGTHAI%TYPE
)
AS
BEGIN
UPDATE KHACHHANG
SET HOTEN=IN_HOTEN,
NGAYSINH=IN_NGAYSINH, 
CMND=IN_CMND,
GIOITINH=IN_GIOITINH, 
DIACHI=IN_DIACHI, 
EMAIL=IN_EMAIL, 
SDT=IN_SDT,
TRANGTHAI=IN_TRANGTHAI
WHERE MAKHACHHANG=IN_MAKHACHHANG;
COMMIT;
END;

--xoa khach hang
CREATE OR REPLACE PROCEDURE XOAKHACHHANG(
IN_MAKHACHHANG KHACHHANG.MAKHACHHANG%TYPE)
AS
BEGIN
DELETE FROM KHACHHANG WHERE MAKHACHHANG=IN_MAKHACHHANG;
COMMIT;
END;

-- tim kiem thong tin hoa don
CREATE OR REPLACE PROCEDURE PRO_TIMKIEMTHONGTINHOADON(
IN_MAPHONG KHACHHANG.HOTEN%TYPE,
IN_MALOAIPHONG KHACHHANG.HOTEN%TYPE,
IN_TENLOAIPHONG LOAIPHONG.TENLOAIPHONG%TYPE,
IN_TRANGTHAI PHONG.TRANGTHAI%TYPE,
IN_GIAPHONG KHACHHANG.HOTEN%TYPE,
IN_TENKH KHACHHANG.HOTEN%TYPE,
IN_CMNDKH KHACHHANG.HOTEN%TYPE,
IN_NGAYDEN KHACHHANG.HOTEN%TYPE,
IN_NGAYDI KHACHHANG.HOTEN%TYPE,
IN_TENNV KHACHHANG.HOTEN%TYPE,
IN_CMNDNV KHACHHANG.HOTEN%TYPE,
IN_TRANGTHAIHD HOADON.TRANGTHAI%TYPE,
CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT PHONG.MAPHONG
FROM ((((((PHONG LEFT JOIN LOAIPHONG ON PHONG.MALOAIPHONG=LOAIPHONG.MALOAIPHONG)LEFT JOIN HOADON ON PHONG.MAPHONG=HOADON.MAPHONG) LEFT JOIN KHACHHANG ON HOADON.MAKHACHHANG=KHACHHANG.MAKHACHHANG) 
LEFT JOIN NHANVIEN ON HOADON.MANHANVIEN=NHANVIEN.MANHANVIEN)))
WHERE PHONG.MAPHONG LIKE ('%'||(IN_MAPHONG)||'%') OR
LOAIPHONG.MALOAIPHONG LIKE ('%'||(IN_MALOAIPHONG)||'%') OR
LOAIPHONG.TENLOAIPHONG LIKE ('%'||(IN_TENLOAIPHONG)||'%') OR
PHONG.TRANGTHAI LIKE ('%'||(IN_TRANGTHAI)||'%') OR
LOAIPHONG.GIAPHONG LIKE ('%'||(IN_GIAPHONG)||'%') OR
KHACHHANG.HOTEN LIKE ('%'||(IN_TENKH)||'%') OR
KHACHHANG.CMND LIKE ('%'||(IN_CMNDKH)||'%') OR
HOADON.NGAYDEN LIKE ('%'||(IN_NGAYDEN)||'%') OR
HOADON.NGAYDI LIKE ('%'||(IN_NGAYDI)||'%') OR
NHANVIEN.HOTEN LIKE ('%'||(IN_TENNV)||'%') OR
NHANVIEN.CMND LIKE ('%'||(IN_CMNDNV)||'%') OR
HOADON.TRANGTHAI LIKE ('%'||(IN_TRANGTHAIHD)||'%')
ORDER BY PHONG.MAPHONG;
END;


--danh sach dich vu co the dat
CREATE OR REPLACE PROCEDURE PRO_DANHSACHDICHVUCOTHEDATDUOC(
CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT MADICHVU,TENDICHVU,GIATIEN
FROM DICHVU
WHERE TRANGTHAI='Có';
END;

--dat dich vu cho khach hang
CREATE OR REPLACE PROCEDURE PRO_DATDICHVUCHOKHACHHANG(
IN_MADICHVU DICHVU_HOADON.MADICHVU%TYPE,
IN_MAHOADON DICHVU_HOADON.MAHOADON%TYPE,
IN_SOLUONG DICHVU_HOADON.SOLUONG%TYPE)
AS
BEGIN
INSERT INTO DICHVU_HOADON(MADICHVU,MAHOADON,SOLUONG) VALUES(
IN_MADICHVU,IN_MAHOADON,IN_SOLUONG);
COMMIT;
END;

--
CREATE OR REPLACE PROCEDURE THONGTINLUUTRUCACPHONG(
  CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN CONTRO FOR
  SELECT PHONG.MAPHONG,LOAIPHONG.MALOAIPHONG,TENLOAIPHONG,PHONG.TRANGTHAI,LOAIPHONG.GIAPHONG,KHACHHANG.HOTEN AS TEN_KH, KHACHHANG.CMND AS CMND_KH,HOADON.NGAYDEN, HOADON.NGAYDI,NHANVIEN.HOTEN AS TEN_NV,NHANVIEN.CMND AS CMND_NV,
  HOADON.MAHOADON
FROM ((((((PHONG LEFT JOIN LOAIPHONG ON PHONG.MALOAIPHONG=LOAIPHONG.MALOAIPHONG)LEFT JOIN HOADON ON PHONG.MAPHONG=HOADON.MAPHONG) LEFT JOIN KHACHHANG ON HOADON.MAKHACHHANG=KHACHHANG.MAKHACHHANG) 
LEFT JOIN NHANVIEN ON HOADON.MANHANVIEN=NHANVIEN.MANHANVIEN)))
ORDER BY PHONG.MAPHONG;
END;

--
CREATE OR REPLACE PROCEDURE PRO_DANHSACHKHACHHANG(
CONTRO OUT SYS_REFCURSOR
)
AS
BEGIN
OPEN CONTRO FOR
select MAKHACHHANG,HOTEN,NGAYSINH,CMND,GIOITINH,DIACHI,EMAIL,SDT,TRANGTHAI,TENLOAIKHACHHANG from KHACHHANG inner join LOAIKHACHHANG
                    on KHACHHANG.MALOAIKHACHHANG=LOAIKHACHHANG.MALOAIKHACHHANG;
END;

--

CREATE OR REPLACE PROCEDURE PRO_DANHSACHLOAIPHONG(
CONTRO OUT SYS_REFCURSOR)
AS
BEGIN
OPEN CONTRO FOR
SELECT * FROM LOAIPHONG;
END;

-- PHONG
INSERT INTO PHONG VALUES('1','1','C');
INSERT INTO PHONG VALUES('2','1','C');
INSERT INTO PHONG VALUES('3','1','K');
INSERT INTO PHONG VALUES('4','1','K');
INSERT INTO PHONG VALUES('5','1','K');
INSERT INTO PHONG VALUES('6','2','K');
INSERT INTO PHONG VALUES('7','2','K');
INSERT INTO PHONG VALUES('8','2','K');
INSERT INTO PHONG VALUES('9','2','K');
INSERT INTO PHONG VALUES('10','3','K');
INSERT INTO PHONG VALUES('11','3','K');
INSERT INTO PHONG VALUES('12','3','C');
INSERT INTO PHONG VALUES('13','3','C');
INSERT INTO PHONG VALUES('14','3','K');
INSERT INTO PHONG VALUES('15','1','K');
INSERT INTO PHONG VALUES('16','2','C');
INSERT INTO PHONG VALUES('17','3','C');
INSERT INTO PHONG VALUES('18','1','K');
INSERT INTO PHONG VALUES('19','2','C');
INSERT INTO PHONG VALUES('20','1','K');
INSERT INTO PHONG VALUES('21','2','C');
INSERT INTO PHONG VALUES('22','3','K');
INSERT INTO PHONG VALUES('23','3','K');
INSERT INTO PHONG VALUES('24','3','K');
INSERT INTO PHONG VALUES('25','2','C');
INSERT INTO PHONG VALUES('26','2','K');
INSERT INTO PHONG VALUES('27','2','K');
INSERT INTO PHONG VALUES('28','1','C');
INSERT INTO PHONG VALUES('29','1','K');
INSERT INTO PHONG VALUES('30','1','C');
INSERT INTO PHONG VALUES('31','2','C');
INSERT INTO PHONG VALUES('32','2','C');
INSERT INTO PHONG VALUES('33','2','K');
INSERT INTO PHONG VALUES('34','2','K');
INSERT INTO PHONG VALUES('35','3','K');
INSERT INTO PHONG VALUES('36','3','K');
INSERT INTO PHONG VALUES('37','2','C');
INSERT INTO PHONG VALUES('38','2','C');
INSERT INTO PHONG VALUES('39','3','K');
INSERT INTO PHONG VALUES('40','1','C');
INSERT INTO PHONG VALUES('41','1','K');
INSERT INTO PHONG VALUES('42','1','K');
INSERT INTO PHONG VALUES('43','1','C');
INSERT INTO PHONG VALUES('44','2','K');
INSERT INTO PHONG VALUES('45','3','C');
INSERT INTO PHONG VALUES('46','2','K');
INSERT INTO PHONG VALUES('47','2','K');
INSERT INTO PHONG VALUES('48','3','C');
INSERT INTO PHONG VALUES('49','3','K');
INSERT INTO PHONG VALUES('50','3','K');
COMMIT;

--NHAN VIEN

INSERT INTO NHANVIEN VALUES('1','Nguyễn Tiến Thịnh',TO_DATE('25/12/1995','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'124567834','0967856743','5','Nam','thinh@gmail.com','An Giang','Đang làm');
INSERT INTO NHANVIEN VALUES('2','Võ Quốc Khánh',TO_DATE('13/07/1996','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'654390578','0978654824','5','Nam','abc@gmail.com','Cần Thơ','Đang làm');
INSERT INTO NHANVIEN VALUES('3','Phạm Nhật Phúc',TO_DATE('14/03/1994','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'135797473','0789654735','5','Nam','null','Vĩnh Long','Đang làm');
INSERT INTO NHANVIEN VALUES('4','Mai Văn Bảo',TO_DATE('25/12/1995','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'189567403','0879654375','5','Nam','null','Đồng Tháp','Nghỉ làm');
INSERT INTO NHANVIEN VALUES('5','Lê Đức Lâm',TO_DATE('17/04/1991','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'268502648','0968746548','5','Nam','null','Tp. Hồ Chí Minh','Nghỉ làm');
INSERT INTO NHANVIEN VALUES('6','Phan Minh Thiên Sơn',TO_DATE('23/12/1997','DD/MM/YYYY'),TO_DATE('24/10/2010','DD/MM/YYYY'),'263897564','0976582134','9','Nam','null','Đăk Lăk','Đang làm');
INSERT INTO NHANVIEN VALUES('7','Nguyễn Văn An',TO_DATE('27/06/1989','DD/MM/YYYY'),TO_DATE('16/07/2009','DD/MM/YYYY'),'368562735','0976856438','9','Nam','null','Bình Định','Đang làm');
INSERT INTO NHANVIEN VALUES('8','Đặng Hữu Chương',TO_DATE('24/03/1990','DD/MM/YYYY'),TO_DATE('24/10/2010','DD/MM/YYYY'),'986750354','0968646182','9','Nam','null','Quảng Nam','Nghỉ làm');
INSERT INTO NHANVIEN VALUES('9','Vũ Hà Nam Ninh',TO_DATE('17/04/1991','DD/MM/YYYY'),TO_DATE('16/07/2009','DD/MM/YYYY'),'746924364','0354686739','9','Nam','null','Tp. Hồ Chí Minh','Nghỉ làm');
INSERT INTO NHANVIEN VALUES('10','Võ Hoàng Cầm',TO_DATE('24/06/1992','DD/MM/YYYY'),TO_DATE('24/10/2010','DD/MM/YYYY'),'865745361','0987561356','10','Nữ','null','Tiền Giang','Đang làm');
INSERT INTO NHANVIEN VALUES('11','Phạm Tuấn Anh',TO_DATE('27/04/1993','DD/MM/YYYY'),TO_DATE('24/10/2010','DD/MM/YYYY'),'756834510','0968750957','10','Nam','null','Tiền Giang','Đang làm');
INSERT INTO NHANVIEN VALUES('12','Trần Văn Khải',TO_DATE('20/06/1994','DD/MM/YYYY'),TO_DATE('24/10/2010','DD/MM/YYYY'),'757528465','0978654285','10','Nam','null','Tp. Hồ Chí Minh','Đang làm');
INSERT INTO NHANVIEN VALUES('13','Võ Thị Thu Thủy',TO_DATE('27/06/1994','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'756293452','0978657297','10','Nữ','null','Quảng Nam','Đang làm');
INSERT INTO NHANVIEN VALUES('14','Nguyễn Thị Hoài Thương ',TO_DATE('16/06/1996','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'859645192','0978568273','9','Nữ','null','Bình Định','Đang làm');
INSERT INTO NHANVIEN VALUES('15','Nguyễn Minh Phát',TO_DATE('15/07/1995','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'854827924','0978636472','9','Nam','null','Bình Định','Đang làm');
INSERT INTO NHANVIEN VALUES('16','Trần Thị Ngọc Trân',TO_DATE('13/05/1996','DD/MM/YYYY'),TO_DATE('12/03/2009','DD/MM/YYYY'),'756835461','0346597563','9','Nữ','null','Quảng Nam','Nghỉ làm');
INSERT INTO NHANVIEN VALUES('17','Nguyễn Thị Ngọc Trân',TO_DATE('15/07/1995','DD/MM/YYYY'),TO_DATE('24/10/2010','DD/MM/YYYY'),'967858281','0237605794','5','Nữ','null','An Giang','Đang làm');
INSERT INTO NHANVIEN VALUES('18','Lê Nhi','18/04/1996',TO_DATE('16/07/2009','DD/MM/YYYY'),TO_DATE('736253759','DD/MM/YYYY'),'0265789564','5','Nữ','null','An Giang','Đang làm');
INSERT INTO NHANVIEN VALUES('19','Nguyễn Thị Thùy Trang',TO_DATE('24/05/1996','DD/MM/YYYY'),TO_DATE('16/07/2009','DD/MM/YYYY'),'756351846','0956254819','5','Nữ','null','Tp. Hồ Chí Minh','Nghỉ làm');

COMMIT;

--KHACH HANG

Insert into KHACHHANG values(6,'Khách Hàng 6',TO_DATE('01/01/2000','DD/MM/YYYY'),123456,'Nam','Hồ Chí Minh',null,'0167725444','Đang thuê');
Insert into KHACHHANG values(7,'Khách Hàng 7',TO_DATE('01/01/2000','DD/MM/YYYY'),1234567,'Nam','Hồ Chí Minh',null,'0167725444','Đã rời đi');
Insert into KHACHHANG values(3,'Khách Hàng 3',TO_DATE('01/01/2000','DD/MM/YYYY'),1234568,'Nam','Hồ Chí Minh',null,'0167725444','Đã rời đi');
Insert into KHACHHANG values(5,'Khách Hàng 4',TO_DATE('01/01/2000','DD/MM/YYYY'),1234569,'Nam','Hồ Chí Minh',null,'0167725444','Đã rời đi');
Insert into KHACHHANG values(5,'Khách Hàng 5',TO_DATE('01/01/2000','DD/MM/YYYY'),1234569,'Nam','Hồ Chí Minh',null,'0167725444','Đã rời đi');
commit;

--tai khoan
INSERT INTO TAIKHOAN VALUES('1','1','1','admin','123456');
INSERT INTO TAIKHOAN VALUES('2','2','2','asdfghjkl','abc123');
INSERT INTO TAIKHOAN VALUES('3','3','2','zxcvbnm','def456');
INSERT INTO TAIKHOAN VALUES('4','4','2','qwert','asd123');
INSERT INTO TAIKHOAN VALUES('5','5','3','zxcvd','qwe234');
INSERT INTO TAIKHOAN VALUES('6','6','3','mnbv','ph12345');
INSERT INTO TAIKHOAN VALUES('7','7','3','dfgheyh','123df');
INSERT INTO TAIKHOAN VALUES('8','8','2','aqzxws','bgh456');
INSERT INTO TAIKHOAN VALUES('9','9','1','plmnjki','psgy234');
COMMIT;
